// Learn cc.Class:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/class.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/class.html
// Learn Attribute:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/reference/attributes.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/reference/attributes.html
// Learn life-cycle callbacks:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/life-cycle-callbacks.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/life-cycle-callbacks.html

cc.Class({
    extends: cc.Component,

    properties: {
        // foo: {
        //     // ATTRIBUTES:
        //     default: null,        // The default value will be used only when the component attaching
        //                           // to a node for the first time
        //     type: cc.SpriteFrame, // optional, default is typeof default
        //     serializable: true,   // optional, default is true
        // },
        // bar: {
        //     get () {
        //         return this._bar;
        //     },
        //     set (value) {
        //         this._bar = value;
        //     }
        // },
        childContent:cc.Node,
    },

    // LIFE-CYCLE CALLBACKS:

    // onLoad () {},

    // start () {
    //     if (window.wx != undefined) {
    //         // window.wx.showShareMenu({withShareTicket: true});//设置分享按钮，方便获取群id展示群排行榜
    //         this.tex = new cc.Texture2D();
    //         // var openDataContext = wx.getOpenDataContext();
    //         // var sharedCanvas = openDataContext.canvas;
    //         // if (sharedCanvas) {
    //         //     sharedCanvas.width = cc.game.canvas.width * 2;
    //         //     sharedCanvas.height = cc.game.canvas.height * 2;
    //         // }
    //         window.sharedCanvas.width = 1334;
    //         window.sharedCanvas.height = 750;
    //         // window.wx.postMessage({
    //         //     messageType: 3,
    //         //     MAIN_MENU_NUM: "score",
    //         //     score: 10
    //         // });
    //     }
    // },
    //
    // _updateSubDomainCanvas () {
    //     if (!this.tex) {
    //         return;
    //     }
    //     console.log('update childContent');
    //     this.tex.initWithElement(sharedCanvas);
    //     this.tex.handleLoadedTexture();
    //     this.childContent.spriteFrame = new cc.SpriteFrame(this.tex);
    // },
    //
    // update(dt) {
    //     this._updateSubDomainCanvas();
    // },

    previousPage(){
        if (window.wx != undefined) {
            // 发消息给子域
            window.wx.postMessage({
                messageType: 6,
                MAIN_MENU_NUM: "score"
            });
        } else {
            cc.log("上一页。score");
        }
    },

    nextPage(){
        if (window.wx != undefined) {
            // 发消息给子域
            window.wx.postMessage({
                messageType: 7,
                MAIN_MENU_NUM: "score"
            });
        } else {
            cc.log("下一页。score");
        }
    },

    // update (dt) {},
});
