// Learn cc.Class:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/class.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/class.html
// Learn Attribute:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/reference/attributes.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/reference/attributes.html
// Learn life-cycle callbacks:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/life-cycle-callbacks.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/life-cycle-callbacks.html

cc.Class({
    extends: cc.Component,

    properties: {
        // foo: {
        //     // ATTRIBUTES:
        //     default: null,        // The default value will be used only when the component attaching
        //                           // to a node for the first time
        //     type: cc.SpriteFrame, // optional, default is typeof default
        //     serializable: true,   // optional, default is true
        // },
        // bar: {
        //     get () {
        //         return this._bar;
        //     },
        //     set (value) {
        //         this._bar = value;
        //     }
        // },
        nameLabel:cc.Label,
        scoreLabel:cc.Label,
        outlineSprite:cc.Node,
        lockedSprite:cc.Node,
        store:null,
        position:0,
        store:cc.Node,
    },

    // LIFE-CYCLE CALLBACKS:

    onLoad () {
        this.nameLabel = this.node.children[0];
        this.scoreLabel = this.node.children[1];
        this.outlineSprite = this.node.children[3];
        this.lockedSprite = this.node.children[4];
        this.node.on('touchend',  ()=> {
            this.store.onItemClick(this.position);
        }, this);
    },

    start () {

    },

    init(arrow,selected,store,position){
        console.log(arrow);
        this.position = position;
        this.store = store;
        this.nameLabel.getComponent(cc.Label).string = arrow.name;
        this.scoreLabel.getComponent(cc.Label).string = arrow.price;
        this.outlineSprite.active = selected;
        this.lockedSprite.active = arrow.isBought==0;
    },

    setUnLock(){
        this.lockedSprite.active = false;
        console.log('unlock');
    },

    setSelected(selected){
        this.outlineSprite.active = selected;
    },

    isUnLocked(){
        return this.lockedSprite.active == false;
    },

    // update (dt) {},
});
